name: Trigger auto deployment for satellite-monitoring

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/satellite-monitoring-AutoDeployTrigger-edac79e6-be64-4917-87a3-00f0358925b0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SATELLITEMONITORING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SATELLITEMONITORING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SATELLITEMONITORING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.SATELLITEMONITORING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SATELLITEMONITORING_REGISTRY_PASSWORD }}
          containerAppName: satellite-monitoring
          resourceGroup: Monitoring
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


